### PR TITLE
Fix library source import

### PR DESCRIPTION
**Pull request by laxa88**
FTFY, and also, please test your code before doing a PR next time, @zaynyatyi :)

### CODE REVIEW

**Comment by RobDangerous** [comment]
Thanks a lot! And sorry for the trouble.

**Comment by zaynyatyi** [comment]
What was the issue and on which target?

**Comment by laxa88** [comment]
@RobDangerous you're welcome. and it's alright! :)
@zaynyatyi i had the issue with android-native. The source files (.cpp and .h) files weren't being imported along with the libraries. it's fixed now though :D

**Comment by zaynyatyi** [comment]
@laxa88 thanks for response. That was out of my tests. Sorry for troubles :)

**Pull request merged**
